<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Challenge;
use App\Models\ChallengeCategory;

class ChallengeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $challenges = [
["category_name"=>"Pendapatan Terlalu Kecil","name"=>"Pendapatan Asli Daerah (PAD) terlalu rendah","definition"=>"Kinerja Pemerintah Daerah dalam hal memperoleh Pendapatan Asli Daerah (PAD) merupakan faktor kunci dalam menentukan kelayakan kreditnya. PAD adalah total pendapatan yang pada prinsipnya berada di bawah kendali Pemerintah Daerah dan karena itu tunduk pada intervensi untuk perbaikan langsung. Jika Penilaian Diri menunjuk ke Otoritas Daerah yang memiliki sumber pendapatan yang tidak memadai, maka tinjauan menyeluruh atas praktik manajemen pendapatan dan implementasi Rencana Tindakan Peningkatan Pendapatan merupakan langkah sangat penting ke arah peningkatan pendapatan."],
["category_name"=>"Pendapatan Terlalu Kecil","name"=>"Pendapatan Transfer Terlalu Kecil","definition"=>"Akses Otoritas Daerah terhadap transfer keuangan antarpemerintah penting untuk menentukan kelaikan kreditnya. Jika respons Penilaian Diri menunjuk pada Otoritas Daerah yang memiliki pendapatan yangtidak memadai karena transfer yang tidak dapat diprediksi, tidak stabil, dan/atau tertunda dari tingkat pemerintah yang lebih tinggi, maka Otoritas Daerah perlu bekerja sama dengan tingkat pemerintah yang lebih tinggi untuk meningkatkan kemampuan memperkirakan dan ketepatan waktu transfer, terutama yang terkait dengan layanan yang diamanatkan."],
["category_name"=>"Pendapatan Terlalu Kecil","name"=>"Pendapatan Lain-lain (Tidak Berulang) terlalu tinggi","definition"=>"Penggunaan pendapatan tidak berulang oleh Otoritas Daerah dapat mempengaruhi kelaikan kreditnya. Pendapatan tidak berulang adalah komponen total pendapatan yang biasanya berada di bawah kendali Otoritas Daerah dan oleh karena itu tunduk pada intervensi langsungnya untuk membatasi penggunaannya. Jika Penilaian Diri menunjuk pada Otoritas Daerah yang menggunakan pendapatan tidak berulang di masa lalu, maka tinjauan menyeluruh praktik manajemen pendapatan tidak berulang merupakan langkah penting."],
["category_name"=>"Belanja Terlalu Banyak","name"=>"Belanja Pegawai terlalu tinggi","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen belanja pegawai yang efektif, biasanya proporsi belanja usaha terbesar. Otoritas Daerah mewajibkan staf untuk melakukan berbagai tugas dan tanggung jawab atas nama organisasi, sehingga mereka harus memastikan bahwa mereka memiliki staf dengan kualifikasi dan kapasitas yang sesuai untuk secara efektif melaksanakan kegiatan yang dipersyaratkan. Mereka juga harus memastikan bahwa personel menerima gaji mereka serta tunjangan langsung dan tidak langsung, termasuk iuran pensiun."],
["category_name"=>"Belanja Terlalu Banyak","name"=>"Belanja Energi dan Bahan Bakar terlalu tinggi","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen belanja energi dan bahan bakar yang efektif, biasanya komponen penting dalam anggaran. Tingkat kenaikan biaya ini mungkin melebihi kategori belanja lainnya seiring kenaikan harga hidrokarbon. Seperti kategori lain pendapatan dan belanja, penting bagi Otoritas Daerah untuk memahami pola-pola historis dan alasan-alasan penyimpangannya yang signifikan."],
["category_name"=>"Belanja Terlalu Banyak","name"=>"Biaya pemeliharaan terlalu tinggi","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen belanja pemeliharaan aset fisik yang efektif, biasanya komponen penting dalam anggaran. Tinjauan rutin semua kategori belanja dapat menghasilkan informasi penting tentang pola belanja historis dan membantu mengidentifikasi peluang untuk menghemat. Direkomendasikan agar Otoritas Daerah meninjau belanja pemeliharaan untuk menentukan apakah ini masuk akal atau bisa dikurangi."],
["category_name"=>"Belanja Terlalu Banyak","name"=>"Belanja Barang dan Jasa Terlalu Tinggi","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen belanja barang dan jasa yang efektif, biasanya komponen penting dalam anggaran Otoritas Daerah. Di beberapa Otoritas Daerah, pembelian barang dan jasa terpusat, namun dalam banyak kasus ini tersebar di beberapa departemen Otoritas Daerah. Analisis yang cermat terhadap proses pengadaan barang dan jasa menunjukkan apakah Otoritas Daerah mencapai pengadaan ini dengan biaya terendah yang tersedia dan juga membantu mengidentifikasi peluang penghematan biaya."],
["category_name"=>"Manajemen Sumber Daya yang Buruk","name"=>"Masalah Anggaran","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen anggaran yang efektif di berbagai fungsi pemerintah. Penganggaran memerlukan keterlibatan seluruh Otoritas Daerah, dengan unit keuangan yang mengatur informasi yang dibutuhkan untuk mengambil keputusan belanja untuk periode akuntansi berikutnya dalam presentasi anggaran formal. Untuk memperbaiki manajemen dan memperkuat kapasitas perencanaan jangka panjang, Otoritas Daerah perlu membedakan antara anggaran usaha dan anggaran modal (investasi)."],
["category_name"=>"Manajemen Sumber Daya yang Buruk","name"=>"Masalah Margin Usaha","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen margin usaha yang efektif di seluruh fungsi pemerintah. Masalah margin operasi terjadi ketika belanja usaha melebihi pendapatan usaha. Kemungkinan penyebabnya antara lain: a) belanja tak terduga; b) kurangnya pendapatan tak terduga; dan/atau c) pertumbuhan belanja usaha melebihi pertumbuhan pendapatan usaha. Ketidaksesuaian antara pertumbuhan belanja dan pertumbuhan pendapatan menyebabkan defisit terus-menerus yang membuat Otoritas Daerah tidak laik kredit."],
["category_name"=>"Manajemen Sumber Daya yang Buruk","name"=>"Masalah Likuiditas","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen arus kas usaha yang efektif untuk memenuhi kewajiban keuangan. Jika respons Penilaian Diri menunjukkan bahwa Otoritas Daerah mengalami masalah menjaga likuiditas yang memadai (kas yang tersedia), maka pola kekurangan kas harus dipahami. Jika banyak pendapatan Otoritas Daerah berasal dari pajak atau transfer yang menyediakan kas hanya beberapa kali sepanjang tahun dan sebagian besar belanja Otoritas Daerah relatif sama dari bulan ke bulan, maka ada potensi kekurangan kas (yaitu, kesenjangan likuiditas)."],
["category_name"=>"Manajemen Sumber Daya yang Buruk","name"=>"Masalah Utang","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen kewajiban utang yang efektif. Biasanya masalah dengan utang timbul saat aturan dasar manajemen utang dilanggar. Aturan paling dasarnya adalah menggunakan utang jangka panjang hanya untuk tujuan membiayai pengembangan aset jangka panjang seperti infrastruktur, dan utang jangka pendek hanya untuk tujuan manajemen likuiditas. Untuk menghindari pelanggaran aturan dasar ini, Otoritas Daerah seharusnya telah menulis kebijakan dan prosedur untuk mencegah salah manajemen utang."],
["category_name"=>"Manajemen Sumber Daya yang Buruk","name"=>"Masalah Aset","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen aset fisik yang efektif, dengan standarisasi pemeliharaan dan penetapan pedoman berkelanjutan untuk perbaikan dan penggantian aset. Ini juga memerlukan keahlian akuntansi dan manajemen keuangan yang dibutuhkan untuk menghubungkan perencanaan fisik dengan perencanaan keuangan. Meningkatkan manajemen aset memerlukan penetapan informasi dasar dan memperkenalkan penggunaan praktik perencanaan dan penganggaran yang lebih baik. Dengan mengetahui aset apa saja yang dimiliki oleh Otoritas Daerah, termasuk nilai dan kondisinya saat ini, merupakan titik awal yang penting untuk memperbaiki manajemen aset."],
["category_name"=>"Manajemen Sumber Daya yang Buruk","name"=>"Masalah Teknologi Informasi","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen teknologi Informasi yang efektif. Ada beberapa tindakan yang bisa dilakukan untuk mengatasi masalah tersebut, yang diawali dengan penilaian Sistem TI Otoritas Daerah yang ada, termasuk peralatan dan perangkat lunak. Kemampuan sistem TI Otoritas Daerah untuk melacak dan memberikan data penting untuk penganggaran dan akuntansi, penagihan dan pengumpulan pendapatan sumber sendiri, perencanaan pembangunan daerah dan perencanaan penanaman modal dan penganggaran sangat penting untuk manajemen sumber daya."],
["category_name"=>"Manajemen Sumber Daya yang Buruk","name"=>"Masalah Informasi","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen informasi yang efektif, termasuk transparansi, ketepatan waktu, jenis informasi yang tersedia, dan kemampuan untuk mengantisipasi masalah. Tindakan tersebut bisa digunakan untuk mengatasi masalah ini termasuk menyiapkan penilaian peraturan, standar, dan kebijakan; mengidentifikasi tindak lanjut pelatihan; menginformasikan masyarakat sipil; menerbitkan laporan keuangan yang diaudit; memperkenalkan laporan internal bulanan; dan memperkenalkan akuntasi entri ganda dan perkiraan pendapatan dan belanja bulanan."],
["category_name"=>"Manajemen Sumber Daya yang Buruk","name"=>"Pengawasan Lemah","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan pengawasan yang efektif di seluruh fungsi pemerintah. Audit independen tahunan diperlukan untuk mengidentifikasi kekurangan manajemen dan pelaporan keuangan. Dengan melibatkan masyarakat sipil membangun kepercayaan publik terhadap Otoritas Daerah dan meningkatkan kesediaan untuk membayar layanan. Sementara pengawasan pemerintah pusat berada di luar kendali pemerintah daerah, sangat penting untuk memastikan bahwa persyaratan kebijakan, hukum, dan peraturan dipatuhi."],
["category_name"=>"Manajemen Sumber Daya yang Buruk","name"=>"Masalah Personel","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan manajemen personel yang efektif di seluruh fungsi pemerintah. Produktifitas staf yang rendah bisa berdampak langsung pada biaya pegawao Otoritas Daerah atau pelaksanaan pemberian layanan karena dibutuhkan lebih banyak orang daripada biasanya untuk menyelesaikan pekerjaannya. Jika Otoritas Daerah mempekerjakan lebih banyak orang daripada biasanya untuk memberikan layanan, maka belanja pegawai meningkat. Jika Otoritas Daerah tidak mempekerjakan lebih banyak orang daripada biasanya, maka produktivitas rendah tercermin dalam pelaksanaan pemberian layanan yang buruk."],
["category_name"=>"Perencanaan yang Buruk untuk Masa Depan","name"=>"Perencanaan Pembangunan Daerah Buruk","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan kemampuan untuk menyiapkan rencana pembangunan fisik, prekursor fundamental untuk meningkatkan sumber pendapatan dan menyiapkan rencana peningkatan modal dan anggaran. Pendekatan antara bergantung terutama pada penelitian bidang visual yang dilakukan oleh staf Otoritas Daerah. Pendekatan terbaik menggunakan komputer, kamera, dan perangkat lunak Sisitem Informasi Global (Global Information System/GIS)/Sistem Posisi Global (Global Positioning System/GPS), yang meningkatkan kemampuan Otoritas Daerah dan pemangku kepentingannya untuk memberi peringkat terbaik pada peningkatan modal yang dibutuhkan untuk mewujudkan visi."],
["category_name"=>"Perencanaan yang Buruk untuk Masa Depan","name"=>"Perencanaan Penanaman Modal","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan kemampuan untuk mengintegrasikan perencanaan penanaman modal ke dalam perencanaan pembangunan daerah, termasuk upaya untuk mencapai ketahanan terhadap ancaman perubahan iklim dan pengurangan emisi gas rumah kaca di masa depan. Proses penanaman modal harus transparan kepada masyarakat sipil, dan menghubungkan pada anggaran modal dan proses perencanaan keuangan. Cakrawala waktu 15 tahun memberi kesempatan bagi beberapa peserta untuk mengevaluasi efektivitas biaya setiap proyek dan kinerja modal terhadap ketahanan dan tolok ukur karbon rendah."],
["category_name"=>"Perencanaan yang Buruk untuk Masa Depan","name"=>"Perencanaan Keuangan Buruk","definition"=>"Kelaikan kredit Otoritas Daerah menunjukkan kemampuan perencanaan di masa depan melalui perencanaan keuangan yang kuat yang memanfaatkan sebaik-baiknya sumber daya langka yang diintegrasikan ke dalam semua pelaksanaan perencanaan pemerintah. Komponen perencanaan keuangan sangat penting untuk perencanaan pembangunan daerah. Biaya akan mempengaruhi keputusan tentang pembangunan di masa depan. Seiring rencana penanaman modal yang dikembangkan, penting bahwa Otoritas Daerah menentukan perkiraan biaya untuk semua proyek yang diusulkan, termasuk PPP, dalam jangka waktu minimal lima tahun."],
["category_name"=>"Akses Buruk ke Pembiayaan Jangka Panjang","name"=>"Kelaikan Kredit Tidak Diketahui","definition"=>"Agar Otoritas Daerah dapat mengakses pembiayaan jangka panjang, Otoritas Daerah harus menunjukkan kelaikan kreditnya kepada kreditor, investor, dan mitra PPP. Cara paling langsung untuk menunjukkan kelaikan kredit adalah memiliki peringkat kredit publik (berdasarkan skala peringkat nasional Otoritas Daerah) dari lembaga pemeringkat kredit terkemuka. Tidak ada peringkat atau evaluasi pihak ketiga lainnya, calon pemberi pinjaman akan melakukan tugas evaluasi mereka sendiri dengan meninjau laporan keuangan, anggaran, rencana formal, dan kebijakan tertulis yang memberikan informasi tentang bagaimana Otoritas Daerah kemungkinan akan melaksanakannya ke depan."],
["category_name"=>"Akses Buruk ke Pembiayaan Jangka Panjang","name"=>"Sumber Modal Terbatas","definition"=>"Agar Otoritas Daerah dapat mengakses pembiayaan jangka panjang, harus ada pemasok pembiayaan jangka panjang (yaitu, kreditur, investor, dan mitra PPP). Agar Otoritas Daerah menerapkan Rencana investasi modal cerdas iklim, diperlukan akses modal jangka panjang dengan harga terjangkau. Mengingat sangat diperlukannya investasi infrastruktur cerdas iklim oleh Otoritas Daerah, penting untuk memaksimalkan jumlah modal pribadi jangka panjang yang tersedia untuk mendanai rencana penanaman modal Otorita Daerah."],
["category_name"=>"Akses Buruk ke Pembiayaan Jangka Panjang","name"=>"Masalah Lingkungan yang Mendukung","definition"=>"Agar Otoritas Daerah dapat mengakses pembiayaan jangka panjang, harus ada menjadi kerangka kebijakan nasional, peraturan perundang-undangan yang memungkinkan Otoritas Daerah untuk menggunakan berbagai mekanisme pembiayaan. Tidak seperti Tantangan lainnya, sebagian besar tindakan untuk memperbaiki lingkungan yang mendukung perlu diambil oleh pemerintah pusat dan bukan oleh Pemerintah Daerah secara langsung. Mekanisme pembiayaan utang termasuk pinjaman, obligasi, fasilitas pembiayaan bersama, dan Kemitraan Publik-Swasta (PPP)."],
["category_name"=>"Akses Buruk ke Pembiayaan Jangka Panjang","name"=>"Kurangnya Pengalaman Pembiayaan","definition"=>"Agar Otoritas Daerah dapat mengakses pembiayaan jangka panjang untuk infrastruktur penting, perlu dipahami bagaimana mendekati kreditor, investor, dan mitra PPP. Tindakan dimulai dengan mendapatkan layanan penasihat keuangan publik yang berpengalaman yang dibantu oleh insinyur dan akuntan ahli untuk membantu Otoritas Daerah dengan menilai kapasitas peminjamannya, merancang proyek, memilih instrumen pembiayaan yang tepat, mendapatkan peringkat kredit, dan menyelesaikan transaksi pembiayaan percontohan."],
["category_name"=>"Merencanakan Infrastruktur Prioritas","name"=>"Keterbatasan Data dan Informasi","definition"=>"Ketidaktersediaan atau keterbatasan data sektoral, spasial, dan sosial ekonomi yang dibutuhkan untuk menilai kebutuhan riil dan urgensi infrastruktur di lapangan"],
["category_name"=>"Merencanakan Infrastruktur Prioritas","name"=>"Kurangnya Keterlibatan Pemangku Kepentingan","definition"=>"Keterlibatan masyarakat, sektor swasta, dan kelompok rentan dalam proses perencanaan masih minim, menyebabkan hasil perencanaan kurang inklusif dan tidak responsif terhadap kebutuhan lokal."],
["category_name"=>"Merencanakan Infrastruktur Prioritas","name"=>"Kapasitas Teknis Terbatas","definition"=>"Pemda menghadapi keterbatasan sumber daya manusia dan alat bantu teknis dalam menyusun studi kelayakan, perhitungan dampak, atau analisis prioritas proyek infrastruktur."],
["category_name"=>"Merencanakan Infrastruktur Prioritas","name"=>"Lemahnya Integrasi dengan Dokumen Perencanaan","definition"=>"Rencana infrastruktur sering tidak terintegrasi secara konsisten dalam RPJMD, Renstra OPD, dan RKPD, sehingga sulit dieksekusi dalam siklus perencanaan dan penganggaran."],
["category_name"=>"Merencanakan Infrastruktur Prioritas","name"=>"Fragmentasi Antar-OPD atau dengan Pemerintah Pusat dan Kurangnya Koordinasi","definition"=>"Perencanaan infrastruktur kerap dilakukan secara sektoral oleh OPD masing-masing tanpa sinergi lintas sektor atau dengan daerah sekitar dan pemerintah pusat, sehingga mengakibatkan duplikasi, tumpang tindih, atau kurangnya kesinambungan antarprogram."],
["category_name"=>"Pendanaan Pembangunan Infrastruktur Prioritas","name"=>"Keterbatasan Ruang Fiskal APBD","definition"=>"Porsi belanja pegawai dan belanja wajib lainnya dalam APBD sangat besar, menyisakan ruang yang kecil bagi belanja modal atau pembiayaan proyek infrastruktur. Terbatasnya Pendapatan Asli Daerah (PAD)"],
["category_name"=>"Pendanaan Pembangunan Infrastruktur Prioritas","name"=>"Kesiapan Proyek yang Rendah (Project Readiness)","definition"=>"Banyak proyek infrastruktur tidak memiliki dokumen perencanaan minimum seperti feasibility study (FS), DED, atau AMDAL, sehingga tidak memenuhi persyaratan pembiayaan dari pihak luar."],
["category_name"=>"Pendanaan Pembangunan Infrastruktur Prioritas","name"=>"Regulasi dan Prosedur yang Kompleks","definition"=>"Pemda sering menghadapi kerumitan regulasi dan prosedur dalam mengakses sumber pembiayaan alternatif, termasuk proses persetujuan pinjaman dan KPBU dari pusat."],
["category_name"=>"Pendanaan Pembangunan Infrastruktur Prioritas","name"=>"Risiko dan Kekhawatiran terhadap Kewajiban Keuangan Jangka Panjang","definition"=>"Kekhawatiran terhadap beban fiskal masa depan (terutama dari pinjaman) menyebabkan keraguan untuk menggunakan instrumen pembiayaan alternatif, meskipun proyeknya strategis."],
["category_name"=>"Pendanaan Pembangunan Infrastruktur Prioritas","name"=>"Ketidakterpaduan antara Perencanaan, Penganggaran, dan Pembiayaan","definition"=>"Proses perencanaan proyek tidak selalu diselaraskan sejak awal dengan sumber pembiayaan yang tersedia, sehingga menimbulkan ketidaksesuaian pada saat implementasi."],
["category_name"=>"Pendanaan Pembangunan Infrastruktur Prioritas","name"=>"Minimnya Eksplorasi terhadap Sumber Pembiayaan Alternatif","definition"=>"Ketergantungan tinggi pada APBD/APBN dan kurangnya eksplorasi terhadap skema pembiayaan alternatif seperti pinjaman daerah, KPBU, atau pembiayaan hijau."],


        ];

        foreach ($challenges as $challenge) {
            $category_id = ChallengeCategory::where("name", $challenge["category_name"])->first()->id;

            Challenge::create([
                "category_id" => $category_id,
                "name" => $challenge["name"],
                "definition" => $challenge["definition"]
            ]);

        }
    }
}
