<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Gov;

class GovsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $govs = [
            ["code" => "11", "name" => "Aceh", "level" => "Provinsi"],
            ["code" => "12", "name" => "Sumatera Utara", "level" => "Provinsi"],
            ["code" => "13", "name" => "Sumatera Barat", "level" => "Provinsi"],
            ["code" => "14", "name" => "Riau", "level" => "Provinsi"],
            ["code" => "15", "name" => "Jambi", "level" => "Provinsi"],
            ["code" => "16", "name" => "Sumatera Selatan", "level" => "Provinsi"],
            ["code" => "17", "name" => "Bengkulu", "level" => "Provinsi"],
            ["code" => "18", "name" => "Lampung", "level" => "Provinsi"],
            ["code" => "19", "name" => "Kep. Bangka Belitung", "level" => "Provinsi"],
            ["code" => "21", "name" => "Kep. Riau", "level" => "Provinsi"],
            ["code" => "31", "name" => "DKI Jakarta", "level" => "Provinsi"],
            ["code" => "32", "name" => "Jawa Barat", "level" => "Provinsi"],
            ["code" => "33", "name" => "Jawa Tengah", "level" => "Provinsi"],
            ["code" => "34", "name" => "DI Yogyakarta", "level" => "Provinsi"],
            ["code" => "35", "name" => "Jawa Timur", "level" => "Provinsi"],
            ["code" => "36", "name" => "Banten", "level" => "Provinsi"],
            ["code" => "51", "name" => "Bali", "level" => "Provinsi"],
            ["code" => "52", "name" => "Nusa Tenggara Barat", "level" => "Provinsi"],
            ["code" => "53", "name" => "Nusa Tenggara Timur", "level" => "Provinsi"],
            ["code" => "61", "name" => "Kalimantan Barat", "level" => "Provinsi"],
            ["code" => "62", "name" => "Kalimantan Tengah", "level" => "Provinsi"],
            ["code" => "63", "name" => "Kalimantan Selatan", "level" => "Provinsi"],
            ["code" => "64", "name" => "Kalimantan Timur", "level" => "Provinsi"],
            ["code" => "65", "name" => "Kalimantan Utara", "level" => "Provinsi"],
            ["code" => "71", "name" => "Sulawesi Utara", "level" => "Provinsi"],
            ["code" => "72", "name" => "Sulawesi Tengah", "level" => "Provinsi"],
            ["code" => "73", "name" => "Sulawesi Selatan", "level" => "Provinsi"],
            ["code" => "74", "name" => "Sulawesi Tenggara", "level" => "Provinsi"],
            ["code" => "75", "name" => "Gorontalo", "level" => "Provinsi"],
            ["code" => "76", "name" => "Sulawesi Barat", "level" => "Provinsi"],
            ["code" => "81", "name" => "Maluku", "level" => "Provinsi"],
            ["code" => "82", "name" => "Maluku Utara", "level" => "Provinsi"],
            ["code" => "91", "name" => "Papua Barat", "level" => "Provinsi"],
            ["code" => "94", "name" => "Papua", "level" => "Provinsi"],
            ["code" => "1101", "name" => "Kabupaten Simeulue", "level" => "Kabupaten/Kota"],
            ["code" => "1102", "name" => "Kabupaten Aceh Singkil", "level" => "Kabupaten/Kota"],
            ["code" => "1103", "name" => "Kabupaten Aceh Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1104", "name" => "Kabupaten Aceh Tenggara", "level" => "Kabupaten/Kota"],
            ["code" => "1105", "name" => "Kabupaten Aceh Timur", "level" => "Kabupaten/Kota"],
            ["code" => "1106", "name" => "Kabupaten Aceh Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "1107", "name" => "Kabupaten Aceh Barat", "level" => "Kabupaten/Kota"],
            ["code" => "1108", "name" => "Kabupaten Aceh Besar", "level" => "Kabupaten/Kota"],
            ["code" => "1109", "name" => "Kabupaten Pidie", "level" => "Kabupaten/Kota"],
            ["code" => "1110", "name" => "Kabupaten Bireuen", "level" => "Kabupaten/Kota"],
            ["code" => "1111", "name" => "Kabupaten Aceh Utara", "level" => "Kabupaten/Kota"],
            ["code" => "1112", "name" => "Kabupaten Aceh Barat Daya", "level" => "Kabupaten/Kota"],
            ["code" => "1113", "name" => "Kabupaten Gayo Lues", "level" => "Kabupaten/Kota"],
            ["code" => "1114", "name" => "Kabupaten Aceh Tamiang", "level" => "Kabupaten/Kota"],
            ["code" => "1115", "name" => "Kabupaten Nagan Raya", "level" => "Kabupaten/Kota"],
            ["code" => "1116", "name" => "Kabupaten Aceh Jaya", "level" => "Kabupaten/Kota"],
            ["code" => "1117", "name" => "Kabupaten Bener Meriah", "level" => "Kabupaten/Kota"],
            ["code" => "1118", "name" => "Kabupaten Pidie Jaya", "level" => "Kabupaten/Kota"],
            ["code" => "1171", "name" => "Kota Banda Aceh", "level" => "Kabupaten/Kota"],
            ["code" => "1172", "name" => "Kota Sabang", "level" => "Kabupaten/Kota"],
            ["code" => "1173", "name" => "Kota Langsa", "level" => "Kabupaten/Kota"],
            ["code" => "1174", "name" => "Kota Lhokseumawe", "level" => "Kabupaten/Kota"],
            ["code" => "1175", "name" => "Kota Subulussalam", "level" => "Kabupaten/Kota"],
            ["code" => "1201", "name" => "Kabupaten Nias", "level" => "Kabupaten/Kota"],
            ["code" => "1202", "name" => "Kabupaten Mandailing Natal", "level" => "Kabupaten/Kota"],
            ["code" => "1203", "name" => "Kabupaten Tapanuli Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1204", "name" => "Kabupaten Tapanuli Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "1205", "name" => "Kabupaten Tapanuli Utara", "level" => "Kabupaten/Kota"],
            ["code" => "1206", "name" => "Kabupaten Toba Samosir", "level" => "Kabupaten/Kota"],
            ["code" => "1207", "name" => "Kabupaten Labuhan Batu", "level" => "Kabupaten/Kota"],
            ["code" => "1208", "name" => "Kabupaten Asahan", "level" => "Kabupaten/Kota"],
            ["code" => "1209", "name" => "Kabupaten Simalungun", "level" => "Kabupaten/Kota"],
            ["code" => "1210", "name" => "Kabupaten Dairi", "level" => "Kabupaten/Kota"],
            ["code" => "1211", "name" => "Kabupaten Karo", "level" => "Kabupaten/Kota"],
            ["code" => "1212", "name" => "Kabupaten Deli Serdang", "level" => "Kabupaten/Kota"],
            ["code" => "1213", "name" => "Kabupaten Langkat", "level" => "Kabupaten/Kota"],
            ["code" => "1214", "name" => "Kabupaten Nias Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1215", "name" => "Kabupaten Humbang Hasundutan", "level" => "Kabupaten/Kota"],
            ["code" => "1216", "name" => "Kabupaten Pakpak Bharat", "level" => "Kabupaten/Kota"],
            ["code" => "1217", "name" => "Kabupaten Samosir", "level" => "Kabupaten/Kota"],
            ["code" => "1218", "name" => "Kabupaten Serdang Bedagai", "level" => "Kabupaten/Kota"],
            ["code" => "1219", "name" => "Kabupaten Batu Bara", "level" => "Kabupaten/Kota"],
            ["code" => "1220", "name" => "Kabupaten Padang Lawas Utara", "level" => "Kabupaten/Kota"],
            ["code" => "1221", "name" => "Kabupaten Padang Lawas", "level" => "Kabupaten/Kota"],
            ["code" => "1222", "name" => "Kabupaten Labuhan Batu Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1223", "name" => "Kabupaten Labuhan Batu Utara", "level" => "Kabupaten/Kota"],
            ["code" => "1224", "name" => "Kabupaten Nias Utara", "level" => "Kabupaten/Kota"],
            ["code" => "1225", "name" => "Kabupaten Nias Barat", "level" => "Kabupaten/Kota"],
            ["code" => "1271", "name" => "Kota Sibolga", "level" => "Kabupaten/Kota"],
            ["code" => "1272", "name" => "Kota Tanjung Balai", "level" => "Kabupaten/Kota"],
            ["code" => "1273", "name" => "Kota Pematang Siantar", "level" => "Kabupaten/Kota"],
            ["code" => "1274", "name" => "Kota Tebing Tinggi", "level" => "Kabupaten/Kota"],
            ["code" => "1275", "name" => "Kota Medan", "level" => "Kabupaten/Kota"],
            ["code" => "1276", "name" => "Kota Binjai", "level" => "Kabupaten/Kota"],
            ["code" => "1277", "name" => "Kota Padangsidimpuan", "level" => "Kabupaten/Kota"],
            ["code" => "1278", "name" => "Kota Gunungsitoli", "level" => "Kabupaten/Kota"],
            ["code" => "1301", "name" => "Kabupaten Kepulauan Mentawai", "level" => "Kabupaten/Kota"],
            ["code" => "1302", "name" => "Kabupaten Pesisir Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1303", "name" => "Kabupaten Solok", "level" => "Kabupaten/Kota"],
            ["code" => "1304", "name" => "Kabupaten Sijunjung", "level" => "Kabupaten/Kota"],
            ["code" => "1305", "name" => "Kabupaten Tanah Datar", "level" => "Kabupaten/Kota"],
            ["code" => "1306", "name" => "Kabupaten Padang Pariaman", "level" => "Kabupaten/Kota"],
            ["code" => "1307", "name" => "Kabupaten Agam", "level" => "Kabupaten/Kota"],
            ["code" => "1308", "name" => "Kabupaten Lima Puluh Kota", "level" => "Kabupaten/Kota"],
            ["code" => "1309", "name" => "Kabupaten Pasaman", "level" => "Kabupaten/Kota"],
            ["code" => "1310", "name" => "Kabupaten Solok Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1311", "name" => "Kabupaten Dharmasraya", "level" => "Kabupaten/Kota"],
            ["code" => "1312", "name" => "Kabupaten Pasaman Barat", "level" => "Kabupaten/Kota"],
            ["code" => "1371", "name" => "Kota Padang", "level" => "Kabupaten/Kota"],
            ["code" => "1372", "name" => "Kota Solok", "level" => "Kabupaten/Kota"],
            ["code" => "1373", "name" => "Kota Sawah Lunto", "level" => "Kabupaten/Kota"],
            ["code" => "1374", "name" => "Kota Padang Panjang", "level" => "Kabupaten/Kota"],
            ["code" => "1375", "name" => "Kota Bukittinggi", "level" => "Kabupaten/Kota"],
            ["code" => "1376", "name" => "Kota Payakumbuh", "level" => "Kabupaten/Kota"],
            ["code" => "1377", "name" => "Kota Pariaman", "level" => "Kabupaten/Kota"],
            ["code" => "1401", "name" => "Kabupaten Kuantan Singingi", "level" => "Kabupaten/Kota"],
            ["code" => "1402", "name" => "Kabupaten Indragiri Hulu", "level" => "Kabupaten/Kota"],
            ["code" => "1403", "name" => "Kabupaten Indragiri Hilir", "level" => "Kabupaten/Kota"],
            ["code" => "1404", "name" => "Kabupaten Pelalawan", "level" => "Kabupaten/Kota"],
            ["code" => "1405", "name" => "Kabupaten Siak", "level" => "Kabupaten/Kota"],
            ["code" => "1406", "name" => "Kabupaten Kampar", "level" => "Kabupaten/Kota"],
            ["code" => "1407", "name" => "Kabupaten Rokan Hulu", "level" => "Kabupaten/Kota"],
            ["code" => "1408", "name" => "Kabupaten Bengkalis", "level" => "Kabupaten/Kota"],
            ["code" => "1409", "name" => "Kabupaten Rokan Hilir", "level" => "Kabupaten/Kota"],
            ["code" => "1410", "name" => "Kabupaten Kepulauan Meranti", "level" => "Kabupaten/Kota"],
            ["code" => "1471", "name" => "Kota Pekanbaru", "level" => "Kabupaten/Kota"],
            ["code" => "1473", "name" => "Kota Dumai", "level" => "Kabupaten/Kota"],
            ["code" => "1501", "name" => "Kabupaten Kerinci", "level" => "Kabupaten/Kota"],
            ["code" => "1502", "name" => "Kabupaten Merangin", "level" => "Kabupaten/Kota"],
            ["code" => "1503", "name" => "Kabupaten Sarolangun", "level" => "Kabupaten/Kota"],
            ["code" => "1504", "name" => "Kabupaten Batang Hari", "level" => "Kabupaten/Kota"],
            ["code" => "1505", "name" => "Kabupaten Muaro Jambi", "level" => "Kabupaten/Kota"],
            ["code" => "1506", "name" => "Kabupaten Tanjung Jabung Timur", "level" => "Kabupaten/Kota"],
            ["code" => "1507", "name" => "Kabupaten Tanjung Jabung Barat", "level" => "Kabupaten/Kota"],
            ["code" => "1508", "name" => "Kabupaten Tebo", "level" => "Kabupaten/Kota"],
            ["code" => "1509", "name" => "Kabupaten Bungo", "level" => "Kabupaten/Kota"],
            ["code" => "1571", "name" => "Kota Jambi", "level" => "Kabupaten/Kota"],
            ["code" => "1572", "name" => "Kota Sungai Penuh", "level" => "Kabupaten/Kota"],
            ["code" => "1601", "name" => "Kabupaten Ogan Komering Ulu", "level" => "Kabupaten/Kota"],
            ["code" => "1602", "name" => "Kabupaten Ogan Komering Ilir", "level" => "Kabupaten/Kota"],
            ["code" => "1603", "name" => "Kabupaten Muara Enim", "level" => "Kabupaten/Kota"],
            ["code" => "1604", "name" => "Kabupaten Lahat", "level" => "Kabupaten/Kota"],
            ["code" => "1605", "name" => "Kabupaten Musi Rawas", "level" => "Kabupaten/Kota"],
            ["code" => "1606", "name" => "Kabupaten Musi Banyuasin", "level" => "Kabupaten/Kota"],
            ["code" => "1607", "name" => "Kabupaten Banyu Asin", "level" => "Kabupaten/Kota"],
            ["code" => "1608", "name" => "Kabupaten Ogan Komering Ulu Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1609", "name" => "Kabupaten Ogan Komering Ulu Timur", "level" => "Kabupaten/Kota"],
            ["code" => "1610", "name" => "Kabupaten Ogan Ilir", "level" => "Kabupaten/Kota"],
            ["code" => "1611", "name" => "Kabupaten Empat Lawang", "level" => "Kabupaten/Kota"],
            ["code" => "1612", "name" => "Kabupaten Penukal Abab Lematang Ilir", "level" => "Kabupaten/Kota"],
            ["code" => "1613", "name" => "Kabupaten Musi Rawas Utara", "level" => "Kabupaten/Kota"],
            ["code" => "1671", "name" => "Kota Palembang", "level" => "Kabupaten/Kota"],
            ["code" => "1672", "name" => "Kota Prabumulih", "level" => "Kabupaten/Kota"],
            ["code" => "1673", "name" => "Kota Pagar Alam", "level" => "Kabupaten/Kota"],
            ["code" => "1674", "name" => "Kota Lubuklinggau", "level" => "Kabupaten/Kota"],
            ["code" => "1701", "name" => "Kabupaten Bengkulu Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1702", "name" => "Kabupaten Rejang Lebong", "level" => "Kabupaten/Kota"],
            ["code" => "1703", "name" => "Kabupaten Bengkulu Utara", "level" => "Kabupaten/Kota"],
            ["code" => "1704", "name" => "Kabupaten Kaur", "level" => "Kabupaten/Kota"],
            ["code" => "1705", "name" => "Kabupaten Seluma", "level" => "Kabupaten/Kota"],
            ["code" => "1706", "name" => "Kabupaten Mukomuko", "level" => "Kabupaten/Kota"],
            ["code" => "1707", "name" => "Kabupaten Lebong", "level" => "Kabupaten/Kota"],
            ["code" => "1708", "name" => "Kabupaten Kepahiang", "level" => "Kabupaten/Kota"],
            ["code" => "1709", "name" => "Kabupaten Bengkulu Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "1771", "name" => "Kota Bengkulu", "level" => "Kabupaten/Kota"],
            ["code" => "1801", "name" => "Kabupaten Lampung Barat", "level" => "Kabupaten/Kota"],
            ["code" => "1802", "name" => "Kabupaten Tanggamus", "level" => "Kabupaten/Kota"],
            ["code" => "1803", "name" => "Kabupaten Lampung Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1804", "name" => "Kabupaten Lampung Timur", "level" => "Kabupaten/Kota"],
            ["code" => "1805", "name" => "Kabupaten Lampung Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "1806", "name" => "Kabupaten Lampung Utara", "level" => "Kabupaten/Kota"],
            ["code" => "1807", "name" => "Kabupaten Way Kanan", "level" => "Kabupaten/Kota"],
            ["code" => "1808", "name" => "Kabupaten Tulangbawang", "level" => "Kabupaten/Kota"],
            ["code" => "1809", "name" => "Kabupaten Pesawaran", "level" => "Kabupaten/Kota"],
            ["code" => "1810", "name" => "Kabupaten Pringsewu", "level" => "Kabupaten/Kota"],
            ["code" => "1811", "name" => "Kabupaten Mesuji", "level" => "Kabupaten/Kota"],
            ["code" => "1812", "name" => "Kabupaten Tulang Bawang Barat", "level" => "Kabupaten/Kota"],
            ["code" => "1813", "name" => "Kabupaten Pesisir Barat", "level" => "Kabupaten/Kota"],
            ["code" => "1871", "name" => "Kota Bandar Lampung", "level" => "Kabupaten/Kota"],
            ["code" => "1872", "name" => "Kota Metro", "level" => "Kabupaten/Kota"],
            ["code" => "1901", "name" => "Kabupaten Bangka", "level" => "Kabupaten/Kota"],
            ["code" => "1902", "name" => "Kabupaten Belitung", "level" => "Kabupaten/Kota"],
            ["code" => "1903", "name" => "Kabupaten Bangka Barat", "level" => "Kabupaten/Kota"],
            ["code" => "1904", "name" => "Kabupaten Bangka Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "1905", "name" => "Kabupaten Bangka Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "1906", "name" => "Kabupaten Belitung Timur", "level" => "Kabupaten/Kota"],
            ["code" => "1971", "name" => "Kota Pangkal Pinang", "level" => "Kabupaten/Kota"],
            ["code" => "2101", "name" => "Kabupaten Karimun", "level" => "Kabupaten/Kota"],
            ["code" => "2102", "name" => "Kabupaten Bintan", "level" => "Kabupaten/Kota"],
            ["code" => "2103", "name" => "Kabupaten Natuna", "level" => "Kabupaten/Kota"],
            ["code" => "2104", "name" => "Kabupaten Lingga", "level" => "Kabupaten/Kota"],
            ["code" => "2105", "name" => "Kabupaten Kepulauan Anambas", "level" => "Kabupaten/Kota"],
            ["code" => "2171", "name" => "Kota Batam", "level" => "Kabupaten/Kota"],
            ["code" => "2172", "name" => "Kota Tanjung Pinang", "level" => "Kabupaten/Kota"],
            ["code" => "3201", "name" => "Kabupaten Bogor", "level" => "Kabupaten/Kota"],
            ["code" => "3202", "name" => "Kabupaten Sukabumi", "level" => "Kabupaten/Kota"],
            ["code" => "3203", "name" => "Kabupaten Cianjur", "level" => "Kabupaten/Kota"],
            ["code" => "3204", "name" => "Kabupaten Bandung", "level" => "Kabupaten/Kota"],
            ["code" => "3205", "name" => "Kabupaten Garut", "level" => "Kabupaten/Kota"],
            ["code" => "3206", "name" => "Kabupaten Tasikmalaya", "level" => "Kabupaten/Kota"],
            ["code" => "3207", "name" => "Kabupaten Ciamis", "level" => "Kabupaten/Kota"],
            ["code" => "3208", "name" => "Kabupaten Kuningan", "level" => "Kabupaten/Kota"],
            ["code" => "3209", "name" => "Kabupaten Cirebon", "level" => "Kabupaten/Kota"],
            ["code" => "3210", "name" => "Kabupaten Majalengka", "level" => "Kabupaten/Kota"],
            ["code" => "3211", "name" => "Kabupaten Sumedang", "level" => "Kabupaten/Kota"],
            ["code" => "3212", "name" => "Kabupaten Indramayu", "level" => "Kabupaten/Kota"],
            ["code" => "3213", "name" => "Kabupaten Subang", "level" => "Kabupaten/Kota"],
            ["code" => "3214", "name" => "Kabupaten Purwakarta", "level" => "Kabupaten/Kota"],
            ["code" => "3215", "name" => "Kabupaten Karawang", "level" => "Kabupaten/Kota"],
            ["code" => "3216", "name" => "Kabupaten Bekasi", "level" => "Kabupaten/Kota"],
            ["code" => "3217", "name" => "Kabupaten Bandung Barat", "level" => "Kabupaten/Kota"],
            ["code" => "3218", "name" => "Kabupaten Pangandaran", "level" => "Kabupaten/Kota"],
            ["code" => "3271", "name" => "Kota Bogor", "level" => "Kabupaten/Kota"],
            ["code" => "3272", "name" => "Kota Sukabumi", "level" => "Kabupaten/Kota"],
            ["code" => "3273", "name" => "Kota Bandung", "level" => "Kabupaten/Kota"],
            ["code" => "3274", "name" => "Kota Cirebon", "level" => "Kabupaten/Kota"],
            ["code" => "3275", "name" => "Kota Bekasi", "level" => "Kabupaten/Kota"],
            ["code" => "3276", "name" => "Kota Depok", "level" => "Kabupaten/Kota"],
            ["code" => "3277", "name" => "Kota Cimahi", "level" => "Kabupaten/Kota"],
            ["code" => "3278", "name" => "Kota Tasikmalaya", "level" => "Kabupaten/Kota"],
            ["code" => "3279", "name" => "Kota Banjar", "level" => "Kabupaten/Kota"],
            ["code" => "3301", "name" => "Kabupaten Cilacap", "level" => "Kabupaten/Kota"],
            ["code" => "3302", "name" => "Kabupaten Banyumas", "level" => "Kabupaten/Kota"],
            ["code" => "3303", "name" => "Kabupaten Purbalingga", "level" => "Kabupaten/Kota"],
            ["code" => "3304", "name" => "Kabupaten Banjarnegara", "level" => "Kabupaten/Kota"],
            ["code" => "3305", "name" => "Kabupaten Kebumen", "level" => "Kabupaten/Kota"],
            ["code" => "3306", "name" => "Kabupaten Purworejo", "level" => "Kabupaten/Kota"],
            ["code" => "3307", "name" => "Kabupaten Wonosobo", "level" => "Kabupaten/Kota"],
            ["code" => "3308", "name" => "Kabupaten Magelang", "level" => "Kabupaten/Kota"],
            ["code" => "3309", "name" => "Kabupaten Boyolali", "level" => "Kabupaten/Kota"],
            ["code" => "3310", "name" => "Kabupaten Klaten", "level" => "Kabupaten/Kota"],
            ["code" => "3311", "name" => "Kabupaten Sukoharjo", "level" => "Kabupaten/Kota"],
            ["code" => "3312", "name" => "Kabupaten Wonogiri", "level" => "Kabupaten/Kota"],
            ["code" => "3313", "name" => "Kabupaten Karanganyar", "level" => "Kabupaten/Kota"],
            ["code" => "3314", "name" => "Kabupaten Sragen", "level" => "Kabupaten/Kota"],
            ["code" => "3315", "name" => "Kabupaten Grobogan", "level" => "Kabupaten/Kota"],
            ["code" => "3316", "name" => "Kabupaten Blora", "level" => "Kabupaten/Kota"],
            ["code" => "3317", "name" => "Kabupaten Rembang", "level" => "Kabupaten/Kota"],
            ["code" => "3318", "name" => "Kabupaten Pati", "level" => "Kabupaten/Kota"],
            ["code" => "3319", "name" => "Kabupaten Kudus", "level" => "Kabupaten/Kota"],
            ["code" => "3320", "name" => "Kabupaten Jepara", "level" => "Kabupaten/Kota"],
            ["code" => "3321", "name" => "Kabupaten Demak", "level" => "Kabupaten/Kota"],
            ["code" => "3322", "name" => "Kabupaten Semarang", "level" => "Kabupaten/Kota"],
            ["code" => "3323", "name" => "Kabupaten Temanggung", "level" => "Kabupaten/Kota"],
            ["code" => "3324", "name" => "Kabupaten Kendal", "level" => "Kabupaten/Kota"],
            ["code" => "3325", "name" => "Kabupaten Batang", "level" => "Kabupaten/Kota"],
            ["code" => "3326", "name" => "Kabupaten Pekalongan", "level" => "Kabupaten/Kota"],
            ["code" => "3327", "name" => "Kabupaten Pemalang", "level" => "Kabupaten/Kota"],
            ["code" => "3328", "name" => "Kabupaten Tegal", "level" => "Kabupaten/Kota"],
            ["code" => "3329", "name" => "Kabupaten Brebes", "level" => "Kabupaten/Kota"],
            ["code" => "3371", "name" => "Kota Magelang", "level" => "Kabupaten/Kota"],
            ["code" => "3372", "name" => "Kota Surakarta", "level" => "Kabupaten/Kota"],
            ["code" => "3373", "name" => "Kota Salatiga", "level" => "Kabupaten/Kota"],
            ["code" => "3374", "name" => "Kota Semarang", "level" => "Kabupaten/Kota"],
            ["code" => "3375", "name" => "Kota Pekalongan", "level" => "Kabupaten/Kota"],
            ["code" => "3376", "name" => "Kota Tegal", "level" => "Kabupaten/Kota"],
            ["code" => "3401", "name" => "Kabupaten Kulon Progo", "level" => "Kabupaten/Kota"],
            ["code" => "3402", "name" => "Kabupaten Bantul", "level" => "Kabupaten/Kota"],
            ["code" => "3403", "name" => "Kabupaten Gunung Kidul", "level" => "Kabupaten/Kota"],
            ["code" => "3404", "name" => "Kabupaten Sleman", "level" => "Kabupaten/Kota"],
            ["code" => "3471", "name" => "Kota Yogyakarta", "level" => "Kabupaten/Kota"],
            ["code" => "3501", "name" => "Kabupaten Pacitan", "level" => "Kabupaten/Kota"],
            ["code" => "3502", "name" => "Kabupaten Ponorogo", "level" => "Kabupaten/Kota"],
            ["code" => "3503", "name" => "Kabupaten Trenggalek", "level" => "Kabupaten/Kota"],
            ["code" => "3504", "name" => "Kabupaten Tulungagung", "level" => "Kabupaten/Kota"],
            ["code" => "3505", "name" => "Kabupaten Blitar", "level" => "Kabupaten/Kota"],
            ["code" => "3506", "name" => "Kabupaten Kediri", "level" => "Kabupaten/Kota"],
            ["code" => "3507", "name" => "Kabupaten Malang", "level" => "Kabupaten/Kota"],
            ["code" => "3508", "name" => "Kabupaten Lumajang", "level" => "Kabupaten/Kota"],
            ["code" => "3509", "name" => "Kabupaten Jember", "level" => "Kabupaten/Kota"],
            ["code" => "3510", "name" => "Kabupaten Banyuwangi", "level" => "Kabupaten/Kota"],
            ["code" => "3511", "name" => "Kabupaten Bondowoso", "level" => "Kabupaten/Kota"],
            ["code" => "3512", "name" => "Kabupaten Situbondo", "level" => "Kabupaten/Kota"],
            ["code" => "3513", "name" => "Kabupaten Probolinggo", "level" => "Kabupaten/Kota"],
            ["code" => "3514", "name" => "Kabupaten Pasuruan", "level" => "Kabupaten/Kota"],
            ["code" => "3515", "name" => "Kabupaten Sidoarjo", "level" => "Kabupaten/Kota"],
            ["code" => "3516", "name" => "Kabupaten Mojokerto", "level" => "Kabupaten/Kota"],
            ["code" => "3517", "name" => "Kabupaten Jombang", "level" => "Kabupaten/Kota"],
            ["code" => "3518", "name" => "Kabupaten Nganjuk", "level" => "Kabupaten/Kota"],
            ["code" => "3519", "name" => "Kabupaten Madiun", "level" => "Kabupaten/Kota"],
            ["code" => "3520", "name" => "Kabupaten Magetan", "level" => "Kabupaten/Kota"],
            ["code" => "3521", "name" => "Kabupaten Ngawi", "level" => "Kabupaten/Kota"],
            ["code" => "3522", "name" => "Kabupaten Bojonegoro", "level" => "Kabupaten/Kota"],
            ["code" => "3523", "name" => "Kabupaten Tuban", "level" => "Kabupaten/Kota"],
            ["code" => "3524", "name" => "Kabupaten Lamongan", "level" => "Kabupaten/Kota"],
            ["code" => "3525", "name" => "Kabupaten Gresik", "level" => "Kabupaten/Kota"],
            ["code" => "3526", "name" => "Kabupaten Bangkalan", "level" => "Kabupaten/Kota"],
            ["code" => "3527", "name" => "Kabupaten Sampang", "level" => "Kabupaten/Kota"],
            ["code" => "3528", "name" => "Kabupaten Pamekasan", "level" => "Kabupaten/Kota"],
            ["code" => "3529", "name" => "Kabupaten Sumenep", "level" => "Kabupaten/Kota"],
            ["code" => "3571", "name" => "Kota Kediri", "level" => "Kabupaten/Kota"],
            ["code" => "3572", "name" => "Kota Blitar", "level" => "Kabupaten/Kota"],
            ["code" => "3573", "name" => "Kota Malang", "level" => "Kabupaten/Kota"],
            ["code" => "3574", "name" => "Kota Probolinggo", "level" => "Kabupaten/Kota"],
            ["code" => "3575", "name" => "Kota Pasuruan", "level" => "Kabupaten/Kota"],
            ["code" => "3576", "name" => "Kota Mojokerto", "level" => "Kabupaten/Kota"],
            ["code" => "3577", "name" => "Kota Madiun", "level" => "Kabupaten/Kota"],
            ["code" => "3578", "name" => "Kota Surabaya", "level" => "Kabupaten/Kota"],
            ["code" => "3579", "name" => "Kota Batu", "level" => "Kabupaten/Kota"],
            ["code" => "3601", "name" => "Kabupaten Pandeglang", "level" => "Kabupaten/Kota"],
            ["code" => "3602", "name" => "Kabupaten Lebak", "level" => "Kabupaten/Kota"],
            ["code" => "3603", "name" => "Kabupaten Tangerang", "level" => "Kabupaten/Kota"],
            ["code" => "3604", "name" => "Kabupaten Serang", "level" => "Kabupaten/Kota"],
            ["code" => "3671", "name" => "Kota Tangerang", "level" => "Kabupaten/Kota"],
            ["code" => "3672", "name" => "Kota Cilegon", "level" => "Kabupaten/Kota"],
            ["code" => "3673", "name" => "Kota Serang", "level" => "Kabupaten/Kota"],
            ["code" => "3674", "name" => "Kota Tangerang Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "5101", "name" => "Kabupaten Jembrana", "level" => "Kabupaten/Kota"],
            ["code" => "5102", "name" => "Kabupaten Tabanan", "level" => "Kabupaten/Kota"],
            ["code" => "5103", "name" => "Kabupaten Badung", "level" => "Kabupaten/Kota"],
            ["code" => "5104", "name" => "Kabupaten Gianyar", "level" => "Kabupaten/Kota"],
            ["code" => "5105", "name" => "Kabupaten Klungkung", "level" => "Kabupaten/Kota"],
            ["code" => "5106", "name" => "Kabupaten Bangli", "level" => "Kabupaten/Kota"],
            ["code" => "5107", "name" => "Kabupaten Karang Asem", "level" => "Kabupaten/Kota"],
            ["code" => "5108", "name" => "Kabupaten Buleleng", "level" => "Kabupaten/Kota"],
            ["code" => "5171", "name" => "Kota Denpasar", "level" => "Kabupaten/Kota"],
            ["code" => "5201", "name" => "Kabupaten Lombok Barat", "level" => "Kabupaten/Kota"],
            ["code" => "5202", "name" => "Kabupaten Lombok Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "5203", "name" => "Kabupaten Lombok Timur", "level" => "Kabupaten/Kota"],
            ["code" => "5204", "name" => "Kabupaten Sumbawa", "level" => "Kabupaten/Kota"],
            ["code" => "5205", "name" => "Kabupaten Dompu", "level" => "Kabupaten/Kota"],
            ["code" => "5206", "name" => "Kabupaten Bima", "level" => "Kabupaten/Kota"],
            ["code" => "5207", "name" => "Kabupaten Sumbawa Barat", "level" => "Kabupaten/Kota"],
            ["code" => "5208", "name" => "Kabupaten Lombok Utara", "level" => "Kabupaten/Kota"],
            ["code" => "5271", "name" => "Kota Mataram", "level" => "Kabupaten/Kota"],
            ["code" => "5272", "name" => "Kota Bima", "level" => "Kabupaten/Kota"],
            ["code" => "5301", "name" => "Kabupaten Sumba Barat", "level" => "Kabupaten/Kota"],
            ["code" => "5302", "name" => "Kabupaten Sumba Timur", "level" => "Kabupaten/Kota"],
            ["code" => "5303", "name" => "Kabupaten Kupang", "level" => "Kabupaten/Kota"],
            ["code" => "5304", "name" => "Kabupaten Timor Tengah Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "5305", "name" => "Kabupaten Timor Tengah Utara", "level" => "Kabupaten/Kota"],
            ["code" => "5306", "name" => "Kabupaten Belu", "level" => "Kabupaten/Kota"],
            ["code" => "5307", "name" => "Kabupaten Alor", "level" => "Kabupaten/Kota"],
            ["code" => "5308", "name" => "Kabupaten Lembata", "level" => "Kabupaten/Kota"],
            ["code" => "5309", "name" => "Kabupaten Flores Timur", "level" => "Kabupaten/Kota"],
            ["code" => "5310", "name" => "Kabupaten Sikka", "level" => "Kabupaten/Kota"],
            ["code" => "5311", "name" => "Kabupaten Ende", "level" => "Kabupaten/Kota"],
            ["code" => "5312", "name" => "Kabupaten Ngada", "level" => "Kabupaten/Kota"],
            ["code" => "5313", "name" => "Kabupaten Manggarai", "level" => "Kabupaten/Kota"],
            ["code" => "5314", "name" => "Kabupaten Rote Ndao", "level" => "Kabupaten/Kota"],
            ["code" => "5315", "name" => "Kabupaten Manggarai Barat", "level" => "Kabupaten/Kota"],
            ["code" => "5316", "name" => "Kabupaten Sumba Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "5317", "name" => "Kabupaten Sumba Barat Daya", "level" => "Kabupaten/Kota"],
            ["code" => "5318", "name" => "Kabupaten Nagekeo", "level" => "Kabupaten/Kota"],
            ["code" => "5319", "name" => "Kabupaten Manggarai Timur", "level" => "Kabupaten/Kota"],
            ["code" => "5320", "name" => "Kabupaten Sabu Raijua", "level" => "Kabupaten/Kota"],
            ["code" => "5321", "name" => "Kabupaten Malaka", "level" => "Kabupaten/Kota"],
            ["code" => "5371", "name" => "Kota Kupang", "level" => "Kabupaten/Kota"],
            ["code" => "6101", "name" => "Kabupaten Sambas", "level" => "Kabupaten/Kota"],
            ["code" => "6102", "name" => "Kabupaten Bengkayang", "level" => "Kabupaten/Kota"],
            ["code" => "6103", "name" => "Kabupaten Landak", "level" => "Kabupaten/Kota"],
            ["code" => "6104", "name" => "Kabupaten Mempawah", "level" => "Kabupaten/Kota"],
            ["code" => "6105", "name" => "Kabupaten Sanggau", "level" => "Kabupaten/Kota"],
            ["code" => "6106", "name" => "Kabupaten Ketapang", "level" => "Kabupaten/Kota"],
            ["code" => "6107", "name" => "Kabupaten Sintang", "level" => "Kabupaten/Kota"],
            ["code" => "6108", "name" => "Kabupaten Kapuas Hulu", "level" => "Kabupaten/Kota"],
            ["code" => "6109", "name" => "Kabupaten Sekadau", "level" => "Kabupaten/Kota"],
            ["code" => "6110", "name" => "Kabupaten Melawi", "level" => "Kabupaten/Kota"],
            ["code" => "6111", "name" => "Kabupaten Kayong Utara", "level" => "Kabupaten/Kota"],
            ["code" => "6112", "name" => "Kabupaten Kubu Raya", "level" => "Kabupaten/Kota"],
            ["code" => "6171", "name" => "Kota Pontianak", "level" => "Kabupaten/Kota"],
            ["code" => "6172", "name" => "Kota Singkawang", "level" => "Kabupaten/Kota"],
            ["code" => "6201", "name" => "Kabupaten Kotawaringin Barat", "level" => "Kabupaten/Kota"],
            ["code" => "6202", "name" => "Kabupaten Kotawaringin Timur", "level" => "Kabupaten/Kota"],
            ["code" => "6203", "name" => "Kabupaten Kapuas", "level" => "Kabupaten/Kota"],
            ["code" => "6204", "name" => "Kabupaten Barito Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "6205", "name" => "Kabupaten Barito Utara", "level" => "Kabupaten/Kota"],
            ["code" => "6206", "name" => "Kabupaten Sukamara", "level" => "Kabupaten/Kota"],
            ["code" => "6207", "name" => "Kabupaten Lamandau", "level" => "Kabupaten/Kota"],
            ["code" => "6208", "name" => "Kabupaten Seruyan", "level" => "Kabupaten/Kota"],
            ["code" => "6209", "name" => "Kabupaten Katingan", "level" => "Kabupaten/Kota"],
            ["code" => "6210", "name" => "Kabupaten Pulang Pisau", "level" => "Kabupaten/Kota"],
            ["code" => "6211", "name" => "Kabupaten Gunung Mas", "level" => "Kabupaten/Kota"],
            ["code" => "6212", "name" => "Kabupaten Barito Timur", "level" => "Kabupaten/Kota"],
            ["code" => "6213", "name" => "Kabupaten Murung Raya", "level" => "Kabupaten/Kota"],
            ["code" => "6271", "name" => "Kota Palangka Raya", "level" => "Kabupaten/Kota"],
            ["code" => "6301", "name" => "Kabupaten Tanah Laut", "level" => "Kabupaten/Kota"],
            ["code" => "6302", "name" => "Kabupaten Kota Baru", "level" => "Kabupaten/Kota"],
            ["code" => "6303", "name" => "Kabupaten Banjar", "level" => "Kabupaten/Kota"],
            ["code" => "6304", "name" => "Kabupaten Barito Kuala", "level" => "Kabupaten/Kota"],
            ["code" => "6305", "name" => "Kabupaten Tapin", "level" => "Kabupaten/Kota"],
            ["code" => "6306", "name" => "Kabupaten Hulu Sungai Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "6307", "name" => "Kabupaten Hulu Sungai Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "6308", "name" => "Kabupaten Hulu Sungai Utara", "level" => "Kabupaten/Kota"],
            ["code" => "6309", "name" => "Kabupaten Tabalong", "level" => "Kabupaten/Kota"],
            ["code" => "6310", "name" => "Kabupaten Tanah Bumbu", "level" => "Kabupaten/Kota"],
            ["code" => "6311", "name" => "Kabupaten Balangan", "level" => "Kabupaten/Kota"],
            ["code" => "6371", "name" => "Kota Banjarmasin", "level" => "Kabupaten/Kota"],
            ["code" => "6372", "name" => "Kota Banjar Baru", "level" => "Kabupaten/Kota"],
            ["code" => "6401", "name" => "Kabupaten Paser", "level" => "Kabupaten/Kota"],
            ["code" => "6402", "name" => "Kabupaten Kutai Barat", "level" => "Kabupaten/Kota"],
            ["code" => "6403", "name" => "Kabupaten Kutai Kartanegara", "level" => "Kabupaten/Kota"],
            ["code" => "6404", "name" => "Kabupaten Kutai Timur", "level" => "Kabupaten/Kota"],
            ["code" => "6405", "name" => "Kabupaten Berau", "level" => "Kabupaten/Kota"],
            ["code" => "6409", "name" => "Kabupaten Penajam Paser Utara", "level" => "Kabupaten/Kota"],
            ["code" => "6411", "name" => "Kabupaten Mahakam Hulu", "level" => "Kabupaten/Kota"],
            ["code" => "6471", "name" => "Kota Balikpapan", "level" => "Kabupaten/Kota"],
            ["code" => "6472", "name" => "Kota Samarinda", "level" => "Kabupaten/Kota"],
            ["code" => "6474", "name" => "Kota Bontang", "level" => "Kabupaten/Kota"],
            ["code" => "6501", "name" => "Kabupaten Malinau", "level" => "Kabupaten/Kota"],
            ["code" => "6502", "name" => "Kabupaten Bulungan", "level" => "Kabupaten/Kota"],
            ["code" => "6503", "name" => "Kabupaten Tana Tidung", "level" => "Kabupaten/Kota"],
            ["code" => "6504", "name" => "Kabupaten Nunukan", "level" => "Kabupaten/Kota"],
            ["code" => "6571", "name" => "Kota Tarakan", "level" => "Kabupaten/Kota"],
            ["code" => "7101", "name" => "Kabupaten Bolaang Mongondow", "level" => "Kabupaten/Kota"],
            ["code" => "7102", "name" => "Kabupaten Minahasa", "level" => "Kabupaten/Kota"],
            ["code" => "7103", "name" => "Kabupaten Kepulauan Sangihe", "level" => "Kabupaten/Kota"],
            ["code" => "7104", "name" => "Kabupaten Kepulauan Talaud", "level" => "Kabupaten/Kota"],
            ["code" => "7105", "name" => "Kabupaten Minahasa Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "7106", "name" => "Kabupaten Minahasa Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7107", "name" => "Kabupaten Bolaang Mongondow Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7108", "name" => "Kabupaten Siau Tagulandang Biaro", "level" => "Kabupaten/Kota"],
            ["code" => "7109", "name" => "Kabupaten Minahasa Tenggara", "level" => "Kabupaten/Kota"],
            ["code" => "7110", "name" => "Kabupaten Bolaang Mongondow Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "7111", "name" => "Kabupaten Bolaang Mongondow Timur", "level" => "Kabupaten/Kota"],
            ["code" => "7171", "name" => "Kota Manado", "level" => "Kabupaten/Kota"],
            ["code" => "7172", "name" => "Kota Bitung", "level" => "Kabupaten/Kota"],
            ["code" => "7173", "name" => "Kota Tomohon", "level" => "Kabupaten/Kota"],
            ["code" => "7174", "name" => "Kota Kotamobagu", "level" => "Kabupaten/Kota"],
            ["code" => "7201", "name" => "Kabupaten Banggai Kepulauan", "level" => "Kabupaten/Kota"],
            ["code" => "7202", "name" => "Kabupaten Banggai", "level" => "Kabupaten/Kota"],
            ["code" => "7203", "name" => "Kabupaten Morowali", "level" => "Kabupaten/Kota"],
            ["code" => "7204", "name" => "Kabupaten Poso", "level" => "Kabupaten/Kota"],
            ["code" => "7205", "name" => "Kabupaten Donggala", "level" => "Kabupaten/Kota"],
            ["code" => "7206", "name" => "Kabupaten Toli-Toli", "level" => "Kabupaten/Kota"],
            ["code" => "7207", "name" => "Kabupaten Buol", "level" => "Kabupaten/Kota"],
            ["code" => "7208", "name" => "Kabupaten Parigi Moutong", "level" => "Kabupaten/Kota"],
            ["code" => "7209", "name" => "Kabupaten Tojo Una-Una", "level" => "Kabupaten/Kota"],
            ["code" => "7210", "name" => "Kabupaten Sigi", "level" => "Kabupaten/Kota"],
            ["code" => "7211", "name" => "Kabupaten Banggai Laut", "level" => "Kabupaten/Kota"],
            ["code" => "7212", "name" => "Kabupaten Morowali Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7271", "name" => "Kota Palu", "level" => "Kabupaten/Kota"],
            ["code" => "7301", "name" => "Kabupaten Kepulauan Selayar", "level" => "Kabupaten/Kota"],
            ["code" => "7302", "name" => "Kabupaten Bulukumba", "level" => "Kabupaten/Kota"],
            ["code" => "7303", "name" => "Kabupaten Bantaeng", "level" => "Kabupaten/Kota"],
            ["code" => "7304", "name" => "Kabupaten Jeneponto", "level" => "Kabupaten/Kota"],
            ["code" => "7305", "name" => "Kabupaten Takalar", "level" => "Kabupaten/Kota"],
            ["code" => "7306", "name" => "Kabupaten Gowa", "level" => "Kabupaten/Kota"],
            ["code" => "7307", "name" => "Kabupaten Sinjai", "level" => "Kabupaten/Kota"],
            ["code" => "7308", "name" => "Kabupaten Maros", "level" => "Kabupaten/Kota"],
            ["code" => "7309", "name" => "Kabupaten Pangkajene Dan Kepulauan", "level" => "Kabupaten/Kota"],
            ["code" => "7310", "name" => "Kabupaten Barru", "level" => "Kabupaten/Kota"],
            ["code" => "7311", "name" => "Kabupaten Bone", "level" => "Kabupaten/Kota"],
            ["code" => "7312", "name" => "Kabupaten Soppeng", "level" => "Kabupaten/Kota"],
            ["code" => "7313", "name" => "Kabupaten Wajo", "level" => "Kabupaten/Kota"],
            ["code" => "7314", "name" => "Kabupaten Sidenreng Rappang", "level" => "Kabupaten/Kota"],
            ["code" => "7315", "name" => "Kabupaten Pinrang", "level" => "Kabupaten/Kota"],
            ["code" => "7316", "name" => "Kabupaten Enrekang", "level" => "Kabupaten/Kota"],
            ["code" => "7317", "name" => "Kabupaten Luwu", "level" => "Kabupaten/Kota"],
            ["code" => "7318", "name" => "Kabupaten Tana Toraja", "level" => "Kabupaten/Kota"],
            ["code" => "7322", "name" => "Kabupaten Luwu Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7325", "name" => "Kabupaten Luwu Timur", "level" => "Kabupaten/Kota"],
            ["code" => "7326", "name" => "Kabupaten Toraja Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7371", "name" => "Kota Makassar", "level" => "Kabupaten/Kota"],
            ["code" => "7372", "name" => "Kota Parepare", "level" => "Kabupaten/Kota"],
            ["code" => "7373", "name" => "Kota Palopo", "level" => "Kabupaten/Kota"],
            ["code" => "7401", "name" => "Kabupaten Buton", "level" => "Kabupaten/Kota"],
            ["code" => "7402", "name" => "Kabupaten Muna", "level" => "Kabupaten/Kota"],
            ["code" => "7403", "name" => "Kabupaten Konawe", "level" => "Kabupaten/Kota"],
            ["code" => "7404", "name" => "Kabupaten Kolaka", "level" => "Kabupaten/Kota"],
            ["code" => "7405", "name" => "Kabupaten Konawe Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "7406", "name" => "Kabupaten Bombana", "level" => "Kabupaten/Kota"],
            ["code" => "7407", "name" => "Kabupaten Wakatobi", "level" => "Kabupaten/Kota"],
            ["code" => "7408", "name" => "Kabupaten Kolaka Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7409", "name" => "Kabupaten Buton Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7410", "name" => "Kabupaten Konawe Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7411", "name" => "Kabupaten Kolaka Timur", "level" => "Kabupaten/Kota"],
            ["code" => "7412", "name" => "Kabupaten Konawe Kepulauan", "level" => "Kabupaten/Kota"],
            ["code" => "7413", "name" => "Kabupaten Muna Barat", "level" => "Kabupaten/Kota"],
            ["code" => "7414", "name" => "Kabupaten Buton Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "7415", "name" => "Kabupaten Buton Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "7471", "name" => "Kota Kendari", "level" => "Kabupaten/Kota"],
            ["code" => "7472", "name" => "Kota Baubau", "level" => "Kabupaten/Kota"],
            ["code" => "7501", "name" => "Kabupaten Boalemo", "level" => "Kabupaten/Kota"],
            ["code" => "7502", "name" => "Kabupaten Gorontalo", "level" => "Kabupaten/Kota"],
            ["code" => "7503", "name" => "Kabupaten Pohuwato", "level" => "Kabupaten/Kota"],
            ["code" => "7504", "name" => "Kabupaten Bone Bolango", "level" => "Kabupaten/Kota"],
            ["code" => "7505", "name" => "Kabupaten Gorontalo Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7571", "name" => "Kota Gorontalo", "level" => "Kabupaten/Kota"],
            ["code" => "7601", "name" => "Kabupaten Majene", "level" => "Kabupaten/Kota"],
            ["code" => "7602", "name" => "Kabupaten Polewali Mandar", "level" => "Kabupaten/Kota"],
            ["code" => "7603", "name" => "Kabupaten Mamasa", "level" => "Kabupaten/Kota"],
            ["code" => "7604", "name" => "Kabupaten Mamuju", "level" => "Kabupaten/Kota"],
            ["code" => "7605", "name" => "Kabupaten Mamuju Utara", "level" => "Kabupaten/Kota"],
            ["code" => "7606", "name" => "Kabupaten Mamuju Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "8101", "name" => "Kabupaten Maluku Tenggara Barat", "level" => "Kabupaten/Kota"],
            ["code" => "8102", "name" => "Kabupaten Maluku Tenggara", "level" => "Kabupaten/Kota"],
            ["code" => "8103", "name" => "Kabupaten Maluku Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "8104", "name" => "Kabupaten Buru", "level" => "Kabupaten/Kota"],
            ["code" => "8105", "name" => "Kabupaten Kepulauan Aru", "level" => "Kabupaten/Kota"],
            ["code" => "8106", "name" => "Kabupaten Seram Bagian Barat", "level" => "Kabupaten/Kota"],
            ["code" => "8107", "name" => "Kabupaten Seram Bagian Timur", "level" => "Kabupaten/Kota"],
            ["code" => "8108", "name" => "Kabupaten Maluku Barat Daya", "level" => "Kabupaten/Kota"],
            ["code" => "8109", "name" => "Kabupaten Buru Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "8171", "name" => "Kota Ambon", "level" => "Kabupaten/Kota"],
            ["code" => "8172", "name" => "Kota Tual", "level" => "Kabupaten/Kota"],
            ["code" => "8201", "name" => "Kabupaten Halmahera Barat", "level" => "Kabupaten/Kota"],
            ["code" => "8202", "name" => "Kabupaten Halmahera Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "8203", "name" => "Kabupaten Kepulauan Sula", "level" => "Kabupaten/Kota"],
            ["code" => "8204", "name" => "Kabupaten Halmahera Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "8205", "name" => "Kabupaten Halmahera Utara", "level" => "Kabupaten/Kota"],
            ["code" => "8206", "name" => "Kabupaten Halmahera Timur", "level" => "Kabupaten/Kota"],
            ["code" => "8207", "name" => "Kabupaten Pulau Morotai", "level" => "Kabupaten/Kota"],
            ["code" => "8208", "name" => "Kabupaten Pulau Taliabu", "level" => "Kabupaten/Kota"],
            ["code" => "8271", "name" => "Kota Ternate", "level" => "Kabupaten/Kota"],
            ["code" => "8272", "name" => "Kota Tidore Kepulauan", "level" => "Kabupaten/Kota"],
            ["code" => "9101", "name" => "Kabupaten Fakfak", "level" => "Kabupaten/Kota"],
            ["code" => "9102", "name" => "Kabupaten Kaimana", "level" => "Kabupaten/Kota"],
            ["code" => "9103", "name" => "Kabupaten Teluk Wondama", "level" => "Kabupaten/Kota"],
            ["code" => "9104", "name" => "Kabupaten Teluk Bintuni", "level" => "Kabupaten/Kota"],
            ["code" => "9105", "name" => "Kabupaten Manokwari", "level" => "Kabupaten/Kota"],
            ["code" => "9106", "name" => "Kabupaten Sorong Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "9107", "name" => "Kabupaten Sorong", "level" => "Kabupaten/Kota"],
            ["code" => "9108", "name" => "Kabupaten Raja Ampat", "level" => "Kabupaten/Kota"],
            ["code" => "9109", "name" => "Kabupaten Tambrauw", "level" => "Kabupaten/Kota"],
            ["code" => "9110", "name" => "Kabupaten Maybrat", "level" => "Kabupaten/Kota"],
            ["code" => "9111", "name" => "Kabupaten Manokwari Selatan", "level" => "Kabupaten/Kota"],
            ["code" => "9112", "name" => "Kabupaten Pegunungan Arfak", "level" => "Kabupaten/Kota"],
            ["code" => "9171", "name" => "Kota Sorong", "level" => "Kabupaten/Kota"],
            ["code" => "9401", "name" => "Kabupaten Merauke", "level" => "Kabupaten/Kota"],
            ["code" => "9402", "name" => "Kabupaten Jayawijaya", "level" => "Kabupaten/Kota"],
            ["code" => "9403", "name" => "Kabupaten Jayapura", "level" => "Kabupaten/Kota"],
            ["code" => "9404", "name" => "Kabupaten Nabire", "level" => "Kabupaten/Kota"],
            ["code" => "9408", "name" => "Kabupaten Kepulauan Yapen", "level" => "Kabupaten/Kota"],
            ["code" => "9409", "name" => "Kabupaten Biak Numfor", "level" => "Kabupaten/Kota"],
            ["code" => "9410", "name" => "Kabupaten Paniai", "level" => "Kabupaten/Kota"],
            ["code" => "9411", "name" => "Kabupaten Puncak Jaya", "level" => "Kabupaten/Kota"],
            ["code" => "9412", "name" => "Kabupaten Mimika", "level" => "Kabupaten/Kota"],
            ["code" => "9413", "name" => "Kabupaten Boven Digoel", "level" => "Kabupaten/Kota"],
            ["code" => "9414", "name" => "Kabupaten Mappi", "level" => "Kabupaten/Kota"],
            ["code" => "9415", "name" => "Kabupaten Asmat", "level" => "Kabupaten/Kota"],
            ["code" => "9416", "name" => "Kabupaten Yahukimo", "level" => "Kabupaten/Kota"],
            ["code" => "9417", "name" => "Kabupaten Pegunungan Bintang", "level" => "Kabupaten/Kota"],
            ["code" => "9418", "name" => "Kabupaten Tolikara", "level" => "Kabupaten/Kota"],
            ["code" => "9419", "name" => "Kabupaten Sarmi", "level" => "Kabupaten/Kota"],
            ["code" => "9420", "name" => "Kabupaten Keerom", "level" => "Kabupaten/Kota"],
            ["code" => "9426", "name" => "Kabupaten Waropen", "level" => "Kabupaten/Kota"],
            ["code" => "9427", "name" => "Kabupaten Supiori", "level" => "Kabupaten/Kota"],
            ["code" => "9428", "name" => "Kabupaten Mamberamo Raya", "level" => "Kabupaten/Kota"],
            ["code" => "9429", "name" => "Kabupaten Nduga", "level" => "Kabupaten/Kota"],
            ["code" => "9430", "name" => "Kabupaten Lanny Jaya", "level" => "Kabupaten/Kota"],
            ["code" => "9431", "name" => "Kabupaten Mamberamo Tengah", "level" => "Kabupaten/Kota"],
            ["code" => "9432", "name" => "Kabupaten Yalimo", "level" => "Kabupaten/Kota"],
            ["code" => "9433", "name" => "Kabupaten Puncak", "level" => "Kabupaten/Kota"],
            ["code" => "9434", "name" => "Kabupaten Dogiyai", "level" => "Kabupaten/Kota"],
            ["code" => "9435", "name" => "Kabupaten Intan Jaya", "level" => "Kabupaten/Kota"],
            ["code" => "9436", "name" => "Kabupaten Deiyai", "level" => "Kabupaten/Kota"],
            ["code" => "9471", "name" => "Kota Jayapura", "level" => "Kabupaten/Kota"],
        ];

        foreach ($govs as $gov) {
            Gov::create($gov);
        }
    }
}
